export * from "./authApi";
export * from "./censosApi";
export * from "./investigadoresApi";
export * from "./administradoresApi";
export * from "./personalApi"
export * from "./ubicacionesApi"
export * from "./recuperacionApi"
export * from "./InfraestructuraApi"
export * from "./estadisticasApi"